version: "3"
   
services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - ./.env.dev.db
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - ./.env.dev
  s3:
    image: zenko/cloudserver
    volumes:
      - ./s3:/data
    ports: 
      - "8100:8000"
    env_file: 
      - ./.env.dev.s3