# Generated by Django 3.2.6 on 2021-08-23 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipmentdb', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='equipmenttype',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_name'),
        ),
    ]
