# Generated by Django 3.2.6 on 2021-08-26 22:49

from django.db import migrations, models
import equipmentdb.models


class Migration(migrations.Migration):

    dependencies = [
        ('equipmentdb', '0003_auto_20210826_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentfault',
            name='status',
            field=models.IntegerField(choices=[(equipmentdb.models.FaultStatus['NEW'], 0), (equipmentdb.models.FaultStatus['IN_PROGRESS'], 1), (equipmentdb.models.FaultStatus['FIXED'], 2), (equipmentdb.models.FaultStatus['UNFIXABLE'], 3)], default=0),
        ),
    ]
