# Generated by Django 3.2.6 on 2021-08-27 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipmentdb', '0006_auto_20210827_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmenttest',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='equipmenttest',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipmenttest',
            name='passed',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
